# See ingest/README.md for all available data
data_provenances:
  - gisaid
  - open
variant_classifications:
  - nextstrain_clades
  - pango_lineages
geo_resolutions:
  - global

# Params for the prepare data scripts
# Define params for each data_provenance / variant_classification / geo_resolution combination
# Include `max_date` if you don't want to use today as the max date
prepare_data:
  gisaid:
    nextstrain_clades:
      global:
        included_days: 150
        location_min_seq: 100
        location_min_seq_days: 30
        excluded_locations: "defaults/global_excluded_locations.txt"
        prune_seq_days: 12
        clade_min_seq: 5000
        clade_min_seq_days: 150
    pango_lineages:
      global:
        included_days: 150
        location_min_seq: 300
        location_min_seq_days: 30
        excluded_locations: "defaults/global_excluded_locations.txt"
        prune_seq_days: 12
        clade_min_seq: 1
        clade_min_seq_days: 150
        collapse_threshold: 350
  open:
    nextstrain_clades:
      global:
        included_days: 150
        location_min_seq: 100
        location_min_seq_days: 30
        excluded_locations: "defaults/global_excluded_locations.txt"
        prune_seq_days: 12
        clade_min_seq: 5000
        clade_min_seq_days: 150
    pango_lineages:
      global:
        included_days: 150
        location_min_seq: 300
        location_min_seq_days: 30
        excluded_locations: "defaults/global_excluded_locations.txt"
        prune_seq_days: 12
        clade_min_seq: 1
        clade_min_seq_days: 150
        collapse_threshold: 350

# Params for the model run scripts
models:
  gisaid:
    nextstrain_clades:
      global:
        pivot: "23A"
    pango_lineages:
      global:
        pivot: "XBB.1.5"
  open:
    nextstrain_clades:
      global:
        pivot: "23A"
    pango_lineages:
      global:
        pivot: "XBB.1.5"

# Model configs
mlr_config: "config/mlr-config.yaml"
# don't run renewal model by default
#renewal_config: "config/renewal-config.yaml"


# A mapping between nextstrain clades, defining pango lineages and clade colours.
# Colours will be assigned to pango lineages by first associating it with its
# corresponding nextstrain clade and then interpolating colours close to the
# clade's colour; this allows each individual lineage to have its own colour
# whilst being able to visually associate them back to their nextstrain clade.
#
# The order in the list must be hierarchical w.r.t pango lineages, i.e. XBB.1.9
# must appear _before_ XBB
#
# NOTES:
# * Lineages are ordered (in the legend & for the GA estimates) alphabetically
#   via their full pango name. This doesn't map nicely onto nextstrain clade
#   definitions, which is why an individual colour scale defined here may appear
#   in multiple parts of the graph.
# * Lineages which are not a descendant of a clade-defining lineage will be
#   grouped as 'other'
clade_definitions:
  - clade: "23F"
    display_name: "23F (EG.5.1)"
    defining_lineage: "EG.5.1"
    color: '#DC2F24'
  - clade: "23E"
    display_name: "23E (XBB.2.3)"
    defining_lineage: "XBB.2.3"
    color: '#E68133'
  - clade: "23D"
    display_name: "23D (XBB.1.9)"
    defining_lineage: "XBB.1.9"
    color: '#D4B13F'
  - clade: "23C"
    display_name: "23C (CH.1.1)"
    defining_lineage: "CH.1.1"
    color: '#A6BE55'
  - clade: "23B"
    display_name: "23B (XBB.1.1)"
    defining_lineage: "XBB.1.1"
    color: '#75B681'
  - clade: "22F"
    display_name: "22F (XBB)"
    defining_lineage: "XBB"
    color: '#3F63CF'
  - clade: "23A"
    display_name: "23A (XBB.1.5)"
    defining_lineage: "XBB.1.5"
    color: '#529AB6'
  - clade: "other"
    display_name: "other"
    defining_lineage: False
    color: '#777777'