# See ingest/README.md for all available data
data_provenances:
  - gisaid
variant_classifications:
  - nextstrain_clades
geo_resolutions:
  - global

# Params for the prepare data scripts
# Define params for each data_provenance / variant_classification / geo_resolution combination
# Include `max_date` if you don't want to use today as the max date
prepare_data:
  gisaid:
    nextstrain_clades:
      global:
        included_days: 450
        location_min_seq: 12000
        location_min_seq_days: 450
        excluded_locations: "defaults/global_excluded_locations.txt"
        prune_seq_days: 12
        clade_min_seq: 5000
        clade_min_seq_days: 450
    pango_lineages:
      global:
        included_days: 150
        location_min_seq: 1500
        location_min_seq_days: 30
        excluded_locations: "defaults/global_excluded_locations.txt"
        prune_seq_days: 12
        clade_min_seq: 1
        clade_min_seq_days: 150
        collapse_threshold: 350
  open:
    nextstrain_clades:
      global:
        included_days: 150
        location_min_seq: 500
        location_min_seq_days: 30
        excluded_locations: "defaults/global_excluded_locations.txt"
        prune_seq_days: 12
        clade_min_seq: 5000
        clade_min_seq_days: 150
    pango_lineages:
      global:
        included_days: 150
        location_min_seq: 1200
        location_min_seq_days: 30
        excluded_locations: "defaults/global_excluded_locations.txt"
        prune_seq_days: 12
        clade_min_seq: 1
        clade_min_seq_days: 150
        collapse_threshold: 350

# Params for the model run scripts
models:
  gisaid:
    nextstrain_clades:
      global:
        pivot: "'21L (Omicron)'"
    pango_lineages:
      global:
        pivot: "XBB.1.5"
  open:
    nextstrain_clades:
      global:
        pivot: "'23A (Omicron)'"
    pango_lineages:
      global:
        pivot: "XBB.1.5"

# Model configs
mlr_config: "config/mlr-config.yaml"
# don't run renewal model by default
#renewal_config: "config/renewal-config.yaml"
